[package]
name = "min-review-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1.58"
clap = { version = "4.0.25", features = ["derive"] }
dotenv = "0.15.0"
jsonwebtoken = "8.1.1"
octocrab = "0.17.0"
thiserror = "1"
tokio = { version = "1.21.2", features = ["full"] }
unidiff = "0.3.3"
