[package]
name = "min-review-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4.0.25", features = ["derive"] }
dotenv = "0.15.0"
octocrab = "0.17.0"
tokio = { version = "1.21.2", features = ["full"] }
