version: '3'
services:
  daemon:
    image: rdelfin/min_review_bot:latest
    volumes:
      - ./config.toml:/etc/reviewbot/config.toml:ro
      - ./private_key.pem:/etc/reviewbot/private_key.pem:ro
      - ./data:/var/cache/reviewbot:rw
      - /var/run/datadog/datadog.sock:/var/run/datadog/datadog.sock
    restart: always
    network_mode: "host"
    command: ["min_review_daemon", "--config", "/etc/reviewbot/config.toml"]
